#!/bin/sh -e

if [ "$1" = configure ]
then
    update-alternatives --install /usr/local/bin/booking-perl booking-perl /usr/local/booking-perl/5.24.1/bin/perl 60 \
        --slave /usr/local/bin/booking-cpanm booking-cpanm /usr/local/booking-perl/5.24.1/bin/cpanm
fi

exit 0
